/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsScheduledToolsRouteImport } from './routes/docs/scheduled-tools'
import { Route as DocsMcpSetupRouteImport } from './routes/docs/mcp-setup'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardSchedulingRouteImport } from './routes/dashboard/scheduling'
import { Route as DashboardRepositoriesRouteImport } from './routes/dashboard/repositories'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardPromptTemplatesRouteRouteImport } from './routes/dashboard/prompt-templates/route'
import { Route as DashboardPromptTemplatesIndexRouteImport } from './routes/dashboard/prompt-templates/index'
import { Route as DashboardPromptTemplatesNewRouteImport } from './routes/dashboard/prompt-templates/new'
import { Route as DashboardPromptTemplatesTemplateIdRouteImport } from './routes/dashboard/prompt-templates/$templateId'
import { Route as ApiOrpcSplatRouteImport } from './routes/api/orpc.$'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DocsScheduledToolsRoute = DocsScheduledToolsRouteImport.update({
  id: '/docs/scheduled-tools',
  path: '/docs/scheduled-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpSetupRoute = DocsMcpSetupRouteImport.update({
  id: '/docs/mcp-setup',
  path: '/docs/mcp-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulingRoute = DashboardSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRepositoriesRoute = DashboardRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPromptTemplatesRouteRoute =
  DashboardPromptTemplatesRouteRouteImport.update({
    id: '/prompt-templates',
    path: '/prompt-templates',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPromptTemplatesIndexRoute =
  DashboardPromptTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPromptTemplatesRouteRoute,
  } as any)
const DashboardPromptTemplatesNewRoute =
  DashboardPromptTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardPromptTemplatesRouteRoute,
  } as any)
const DashboardPromptTemplatesTemplateIdRoute =
  DashboardPromptTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardPromptTemplatesRouteRoute,
  } as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/prompt-templates': typeof DashboardPromptTemplatesRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/docs/mcp-setup': typeof DocsMcpSetupRoute
  '/docs/scheduled-tools': typeof DocsScheduledToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/dashboard/prompt-templates/$templateId': typeof DashboardPromptTemplatesTemplateIdRoute
  '/dashboard/prompt-templates/new': typeof DashboardPromptTemplatesNewRoute
  '/dashboard/prompt-templates/': typeof DashboardPromptTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/docs/mcp-setup': typeof DocsMcpSetupRoute
  '/docs/scheduled-tools': typeof DocsScheduledToolsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/dashboard/prompt-templates/$templateId': typeof DashboardPromptTemplatesTemplateIdRoute
  '/dashboard/prompt-templates/new': typeof DashboardPromptTemplatesNewRoute
  '/dashboard/prompt-templates': typeof DashboardPromptTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/prompt-templates': typeof DashboardPromptTemplatesRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRoute
  '/dashboard/scheduling': typeof DashboardSchedulingRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/docs/mcp-setup': typeof DocsMcpSetupRoute
  '/docs/scheduled-tools': typeof DocsScheduledToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/dashboard/prompt-templates/$templateId': typeof DashboardPromptTemplatesTemplateIdRoute
  '/dashboard/prompt-templates/new': typeof DashboardPromptTemplatesNewRoute
  '/dashboard/prompt-templates/': typeof DashboardPromptTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard/prompt-templates'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/repositories'
    | '/dashboard/scheduling'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/docs/mcp-setup'
    | '/docs/scheduled-tools'
    | '/dashboard/'
    | '/api/orpc/$'
    | '/dashboard/prompt-templates/$templateId'
    | '/dashboard/prompt-templates/new'
    | '/dashboard/prompt-templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/repositories'
    | '/dashboard/scheduling'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/docs/mcp-setup'
    | '/docs/scheduled-tools'
    | '/dashboard'
    | '/api/orpc/$'
    | '/dashboard/prompt-templates/$templateId'
    | '/dashboard/prompt-templates/new'
    | '/dashboard/prompt-templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard/prompt-templates'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/repositories'
    | '/dashboard/scheduling'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/docs/mcp-setup'
    | '/docs/scheduled-tools'
    | '/dashboard/'
    | '/api/orpc/$'
    | '/dashboard/prompt-templates/$templateId'
    | '/dashboard/prompt-templates/new'
    | '/dashboard/prompt-templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  DocsMcpSetupRoute: typeof DocsMcpSetupRoute
  DocsScheduledToolsRoute: typeof DocsScheduledToolsRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/docs/scheduled-tools': {
      id: '/docs/scheduled-tools'
      path: '/docs/scheduled-tools'
      fullPath: '/docs/scheduled-tools'
      preLoaderRoute: typeof DocsScheduledToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp-setup': {
      id: '/docs/mcp-setup'
      path: '/docs/mcp-setup'
      fullPath: '/docs/mcp-setup'
      preLoaderRoute: typeof DocsMcpSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/scheduling': {
      id: '/dashboard/scheduling'
      path: '/scheduling'
      fullPath: '/dashboard/scheduling'
      preLoaderRoute: typeof DashboardSchedulingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/repositories': {
      id: '/dashboard/repositories'
      path: '/repositories'
      fullPath: '/dashboard/repositories'
      preLoaderRoute: typeof DashboardRepositoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/prompt-templates': {
      id: '/dashboard/prompt-templates'
      path: '/prompt-templates'
      fullPath: '/dashboard/prompt-templates'
      preLoaderRoute: typeof DashboardPromptTemplatesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/prompt-templates/': {
      id: '/dashboard/prompt-templates/'
      path: '/'
      fullPath: '/dashboard/prompt-templates/'
      preLoaderRoute: typeof DashboardPromptTemplatesIndexRouteImport
      parentRoute: typeof DashboardPromptTemplatesRouteRoute
    }
    '/dashboard/prompt-templates/new': {
      id: '/dashboard/prompt-templates/new'
      path: '/new'
      fullPath: '/dashboard/prompt-templates/new'
      preLoaderRoute: typeof DashboardPromptTemplatesNewRouteImport
      parentRoute: typeof DashboardPromptTemplatesRouteRoute
    }
    '/dashboard/prompt-templates/$templateId': {
      id: '/dashboard/prompt-templates/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/prompt-templates/$templateId'
      preLoaderRoute: typeof DashboardPromptTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardPromptTemplatesRouteRoute
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardPromptTemplatesRouteRouteChildren {
  DashboardPromptTemplatesTemplateIdRoute: typeof DashboardPromptTemplatesTemplateIdRoute
  DashboardPromptTemplatesNewRoute: typeof DashboardPromptTemplatesNewRoute
  DashboardPromptTemplatesIndexRoute: typeof DashboardPromptTemplatesIndexRoute
}

const DashboardPromptTemplatesRouteRouteChildren: DashboardPromptTemplatesRouteRouteChildren =
  {
    DashboardPromptTemplatesTemplateIdRoute:
      DashboardPromptTemplatesTemplateIdRoute,
    DashboardPromptTemplatesNewRoute: DashboardPromptTemplatesNewRoute,
    DashboardPromptTemplatesIndexRoute: DashboardPromptTemplatesIndexRoute,
  }

const DashboardPromptTemplatesRouteRouteWithChildren =
  DashboardPromptTemplatesRouteRoute._addFileChildren(
    DashboardPromptTemplatesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardPromptTemplatesRouteRoute: typeof DashboardPromptTemplatesRouteRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardRepositoriesRoute: typeof DashboardRepositoriesRoute
  DashboardSchedulingRoute: typeof DashboardSchedulingRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardPromptTemplatesRouteRoute:
    DashboardPromptTemplatesRouteRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardRepositoriesRoute: DashboardRepositoriesRoute,
  DashboardSchedulingRoute: DashboardSchedulingRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DocsMcpSetupRoute: DocsMcpSetupRoute,
  DocsScheduledToolsRoute: DocsScheduledToolsRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
